"""``a2a-bridge`` CLI — setup, start, stop, status.

This module is the single entry point registered via ``pyproject.toml``::

    [project.scripts]
    a2a-bridge = "a2a_bridge.cli:main"
"""

from __future__ import annotations

import argparse
import getpass
import json
import os
import shutil
import signal
import subprocess
import sys
import time
from pathlib import Path
from typing import Any, Optional

from a2a_bridge import __version__

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
CONFIG_DIR = Path.home() / ".a2a-bridge"
CONFIG_FILE = CONFIG_DIR / ".env"
PID_FILE = CONFIG_DIR / "bridge.pid"
LOG_FILE = CONFIG_DIR / "bridge.log"

# ---------------------------------------------------------------------------
# ANSI helpers
# ---------------------------------------------------------------------------
_COLOR = sys.stdout.isatty()


def _c(code: str, text: str) -> str:
    return f"\033[{code}m{text}\033[0m" if _COLOR else text


def _green(t: str) -> str:
    return _c("32", t)


def _yellow(t: str) -> str:
    return _c("33", t)


def _red(t: str) -> str:
    return _c("31", t)


def _bold(t: str) -> str:
    return _c("1", t)


def _ok(msg: str) -> None:
    print(f"  {_green('✓')} {msg}")


def _warn(msg: str) -> None:
    print(f"  {_yellow('!')} {msg}")


def _err(msg: str) -> None:
    print(f"  {_red('✗')} {msg}", file=sys.stderr)


# ---------------------------------------------------------------------------
# Env / config helpers
# ---------------------------------------------------------------------------
def _load_env() -> dict[str, str]:
    """Parse ``~/.a2a-bridge/.env`` into a dict."""
    env: dict[str, str] = {}
    if not CONFIG_FILE.exists():
        return env
    for line in CONFIG_FILE.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        env[key.strip()] = value.strip()
    return env


def _write_env(env: dict[str, str]) -> None:
    """Write a dict to ``~/.a2a-bridge/.env``."""
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by `a2a-bridge setup`",
        f"# {time.strftime('%Y-%m-%d %H:%M:%S')}",
        "",
    ]
    for key, value in env.items():
        lines.append(f"{key}={value}")
    lines.append("")
    CONFIG_FILE.write_text("\n".join(lines))


def _apply_env(env: dict[str, str]) -> None:
    """Inject config values into ``os.environ``."""
    for key, value in env.items():
        if value:  # don't overwrite with empty
            os.environ[key] = value


# ---------------------------------------------------------------------------
# CLI auto-detection
# ---------------------------------------------------------------------------
_CLI_TOOLS = ("codex", "claude", "qoder")


def _detect_clis() -> dict[str, Optional[str]]:
    """Return ``{cli_name: binary_path_or_None}``."""
    result: dict[str, Optional[str]] = {}
    for name in _CLI_TOOLS:
        path = shutil.which(name)
        result[name] = path
    return result


def _print_cli_status(clis: dict[str, Optional[str]]) -> None:
    for name, path in clis.items():
        if path:
            _ok(f"{name:12s} → {path}")
        else:
            _warn(f"{name:12s} → not found")


# ---------------------------------------------------------------------------
# Prompt helper
# ---------------------------------------------------------------------------
def _prompt(label: str, default: str = "", secret: bool = False) -> str:
    suffix = f" [{default}]" if default else ""
    prompt_str = f"  {label}{suffix}: "
    if secret:
        value = getpass.getpass(prompt_str)
    else:
        value = input(prompt_str)
    return value.strip() or default


def _choice(label: str, options: list[str], default: str = "") -> str:
    opts = "/".join(options)
    hint = f" [{default}]" if default else ""
    while True:
        value = input(f"  {label} ({opts}){hint}: ").strip()
        if not value:
            return default
        if value.lower() in [o.lower() for o in options]:
            return value.lower()
        print(f"    Please enter one of: {', '.join(options)}")


# ---------------------------------------------------------------------------
# cmd: setup
# ---------------------------------------------------------------------------
def _cmd_setup(args: argparse.Namespace) -> None:
    """Interactive setup wizard."""
    print()
    print(_bold("  A2A Bridge Setup"))
    print("  " + "─" * 44)
    print()

    existing = _load_env()

    # --- Service ---
    print(f"  {_bold('Service Configuration')}")
    host = _prompt("Listen host", existing.get("BRIDGE_HOST", "0.0.0.0"))
    port = _prompt("Listen port", existing.get("BRIDGE_PORT", "8720"))
    public_url = _prompt("Public URL (blank to auto)", existing.get("BRIDGE_PUBLIC_URL", ""))
    api_key = _prompt("API Key (blank to disable auth)", existing.get("BRIDGE_API_KEY", ""), secret=True)
    print()

    # --- CLI Detection ---
    print(f"  {_bold('Agent CLI Detection')}")
    clis = _detect_clis()
    _print_cli_status(clis)
    print()

    # --- Default agent ---
    available = [n for n, p in clis.items() if p]
    if not available:
        _warn("No agent CLIs detected. Install at least one (codex/claude/qoder).")
        default_agent = "codex"
    else:
        default_agent = available[0]
    default_agent = _prompt("Default agent", existing.get("BRIDGE_DEFAULT_AGENT", default_agent))
    print()

    # --- Execution ---
    print(f"  {_bold('Execution Settings')}")
    work_dir = _prompt("Work directory", existing.get("BRIDGE_WORK_DIR", str(Path.home() / "workspace")))
    concurrency = _prompt("Max concurrency", existing.get("BRIDGE_MAX_CONCURRENCY", "5"))
    timeout = _prompt("Default timeout (seconds)", existing.get("BRIDGE_DEFAULT_TIMEOUT", "600"))
    print()

    # --- LLM Keys ---
    print(f"  {_bold('LLM API Keys')}  (passed through to CLI tools)")
    openai_key = _prompt("OPENAI_API_KEY (blank to skip)", existing.get("OPENAI_API_KEY", ""), secret=True)
    anthropic_key = _prompt("ANTHROPIC_API_KEY (blank to skip)", existing.get("ANTHROPIC_API_KEY", ""), secret=True)
    print()

    # --- Git ---
    print(f"  {_bold('Git Integration')}  (optional)")
    git_repos_dir = _prompt("Git repos dir", existing.get("GIT_REPOS_DIR", "/tmp/a2a-repos"))
    git_default_repo = _prompt("Default repo URL (blank to skip)", existing.get("GIT_DEFAULT_REPO", ""))
    git_default_branch = _prompt("Default base branch", existing.get("GIT_DEFAULT_BRANCH", "main"))
    git_auth_token = _prompt("HTTPS auth token (blank to skip)", existing.get("GIT_AUTH_TOKEN", ""), secret=True)
    git_ssh_key = _prompt("SSH key path (blank to skip)", existing.get("GIT_SSH_KEY_PATH", ""))
    print()

    # --- Build env dict ---
    env: dict[str, str] = {
        "BRIDGE_HOST": host,
        "BRIDGE_PORT": port,
        "BRIDGE_PUBLIC_URL": public_url,
        "BRIDGE_API_KEY": api_key,
        "BRIDGE_WORK_DIR": work_dir,
        "BRIDGE_MAX_CONCURRENCY": concurrency,
        "BRIDGE_DEFAULT_TIMEOUT": timeout,
        "BRIDGE_DEFAULT_AGENT": default_agent,
        "BRIDGE_LOG_LEVEL": existing.get("BRIDGE_LOG_LEVEL", "INFO"),
        "OPENAI_API_KEY": openai_key,
        "ANTHROPIC_API_KEY": anthropic_key,
        "GIT_REPOS_DIR": git_repos_dir,
        "GIT_DEFAULT_REPO": git_default_repo,
        "GIT_DEFAULT_BRANCH": git_default_branch,
        "GIT_AUTH_TOKEN": git_auth_token,
        "GIT_SSH_KEY_PATH": git_ssh_key,
        "GIT_AUTO_PUSH": existing.get("GIT_AUTO_PUSH", "true"),
    }

    _write_env(env)
    _ok(f"Config saved to {CONFIG_FILE}")

    # --- Service registration ---
    if sys.platform != "win32":
        register_service = _choice("Register as system service?", ["y", "n"], "n")
        if register_service == "y":
            _register_system_service()

    print()
    _ok("Setup complete! Run  a2a-bridge start  to launch the bridge.")
    print()


# ---------------------------------------------------------------------------
# cmd: start
# ---------------------------------------------------------------------------
def _cmd_start(args: argparse.Namespace) -> None:
    """Start the A2A Bridge server."""
    # Load config
    env = _load_env()
    host = env.get("BRIDGE_HOST", "0.0.0.0")
    port = env.get("BRIDGE_PORT", "8720")

    if args.daemon:
        _start_daemon(env, host, port, args.log_level)
    else:
        _start_foreground(env, host, port, args.log_level)


def _start_foreground(env: dict[str, str], host: str, port: str, log_level: str) -> None:
    """Run the server in the foreground (Ctrl-C to stop)."""
    _apply_env(env)
    if log_level:
        os.environ["BRIDGE_LOG_LEVEL"] = log_level

    print(f"  {_green('▶')} A2A Bridge starting on {host}:{port}")
    print(f"  Press Ctrl+C to stop")
    print()

    import uvicorn

    uvicorn.run(
        "main:app",
        host=host,
        port=int(port),
        log_level=(log_level or env.get("BRIDGE_LOG_LEVEL", "info")).lower(),
    )


def _start_daemon(env: dict[str, str], host: str, port: str, log_level: str) -> None:
    """Start the server as a background daemon."""
    # Check if already running
    pid = _read_pid()
    if pid and _pid_alive(pid):
        _warn(f"Bridge is already running (PID {pid})")
        return

    CONFIG_DIR.mkdir(parents=True, exist_ok=True)

    # Build environment for subprocess
    sub_env = dict(os.environ)
    sub_env.update({k: v for k, v in env.items() if v})
    if log_level:
        sub_env["BRIDGE_LOG_LEVEL"] = log_level

    log_fh = open(LOG_FILE, "a")
    proc = subprocess.Popen(
        [sys.executable, "-c", "import uvicorn; uvicorn.run('main:app', host='"
         + host + "', port=" + port + ", log_level='"
         + (log_level or env.get("BRIDGE_LOG_LEVEL", "info")).lower() + "')"],
        stdout=log_fh,
        stderr=subprocess.STDOUT,
        start_new_session=True,
        env=sub_env,
    )
    log_fh.close()

    PID_FILE.write_text(str(proc.pid))
    time.sleep(0.5)

    if proc.poll() is not None:
        _err(f"Bridge exited immediately (code={proc.returncode}). Check {LOG_FILE}")
        PID_FILE.unlink(missing_ok=True)
        return

    print()
    _ok(f"Bridge started (PID {proc.pid})")
    _ok(f"Listening on {host}:{port}")
    _ok(f"Logs: {LOG_FILE}")
    _ok(f"Stop: a2a-bridge stop")
    print()


# ---------------------------------------------------------------------------
# cmd: stop
# ---------------------------------------------------------------------------
def _cmd_stop(args: argparse.Namespace) -> None:
    """Stop the running bridge daemon."""
    pid = _read_pid()
    if not pid:
        _warn("No PID file found. Bridge may not be running.")
        return
    if not _pid_alive(pid):
        _warn(f"Process {pid} is not running (stale PID file).")
        PID_FILE.unlink(missing_ok=True)
        return

    print(f"  Stopping bridge (PID {pid})...")
    os.kill(pid, signal.SIGTERM)
    # Wait up to 5 seconds
    for _ in range(50):
        if not _pid_alive(pid):
            break
        time.sleep(0.1)

    if _pid_alive(pid):
        _warn("Graceful stop timed out, sending SIGKILL...")
        os.kill(pid, signal.SIGKILL)
        time.sleep(0.3)

    PID_FILE.unlink(missing_ok=True)
    _ok("Bridge stopped.")


# ---------------------------------------------------------------------------
# cmd: status
# ---------------------------------------------------------------------------
def _cmd_status(args: argparse.Namespace) -> None:
    """Show bridge status and health."""
    print()
    print(f"  {_bold('A2A Bridge Status')}  v{__version__}")
    print("  " + "─" * 44)

    # Config
    if CONFIG_FILE.exists():
        _ok(f"Config: {CONFIG_FILE}")
    else:
        _warn(f"Config not found: {CONFIG_FILE} (run `a2a-bridge setup`)")

    # PID / process
    pid = _read_pid()
    if pid and _pid_alive(pid):
        _ok(f"Running: PID {pid}")
    else:
        _warn("Not running")
        if pid:
            PID_FILE.unlink(missing_ok=True)

    # CLIs
    print()
    print(f"  {_bold('Agent CLIs')}")
    clis = _detect_clis()
    _print_cli_status(clis)

    # Health endpoint
    env = _load_env()
    port = env.get("BRIDGE_PORT", "8720")
    print()
    print(f"  {_bold('Health Endpoint')}")
    print(f"  http://localhost:{port}/health")
    try:
        import urllib.request
        resp = urllib.request.urlopen(f"http://localhost:{port}/health", timeout=2)
        data = json.loads(resp.read())
        _ok(f"Status: {data.get('status', '?')}")
        agents = data.get("agents", [])
        active = data.get("active_tasks", [])
        print(f"  Agents: {', '.join(agents) if agents else '(none)'}")
        print(f"  Active tasks: {len(active)}")
    except Exception:
        _warn("Health endpoint unreachable (bridge not running?)")

    print()


# ---------------------------------------------------------------------------
# cmd: doctor
# ---------------------------------------------------------------------------
def _cmd_doctor(args: argparse.Namespace) -> None:
    """Diagnose common issues."""
    print()
    print(f"  {_bold('A2A Bridge Doctor')}")
    print("  " + "─" * 44)
    issues: list[str] = []

    # Python version
    py_ver = sys.version.split()[0]
    py_major = sys.version_info[:2]
    if py_major >= (3, 11):
        _ok(f"Python {py_ver}")
    else:
        issues.append("Python 3.11+ required")
        _err(f"Python {py_ver} (need 3.11+)")

    # Node.js
    node = shutil.which("node")
    if node:
        try:
            nv = subprocess.check_output(["node", "--version"], text=True).strip()
            _ok(f"Node.js {nv}")
        except Exception:
            _ok(f"Node.js: {node}")
    else:
        issues.append("Node.js 20+ required")
        _err("Node.js not found")

    # Git
    git = shutil.which("git")
    if git:
        try:
            gv = subprocess.check_output(["git", "--version"], text=True).strip()
            _ok(gv)
        except Exception:
            _ok(f"Git: {git}")
    else:
        issues.append("Git required")
        _err("Git not found")

    # CLIs
    print()
    clis = _detect_clis()
    for name, path in clis.items():
        if path:
            _ok(f"{name}: {path}")
        else:
            issues.append(f"{name} CLI not installed")
            _warn(f"{name}: not found (npm install -g ...)")

    # Config
    print()
    if CONFIG_FILE.exists():
        _ok(f"Config: {CONFIG_FILE}")
    else:
        issues.append("No config file")
        _warn("No config (run `a2a-bridge setup`)")

    # Summary
    print()
    if issues:
        print(f"  {_yellow(str(len(issues)))} issue(s) found:")
        for i in issues:
            print(f"    • {i}")
    else:
        _ok("All checks passed!")
    print()


# ---------------------------------------------------------------------------
# System service registration
# ---------------------------------------------------------------------------
def _register_system_service() -> None:
    """Register as a system service (systemd on Linux, launchd on macOS)."""
    if sys.platform == "darwin":
        _register_launchd()
    elif sys.platform == "linux":
        _register_systemd()
    else:
        _warn(f"Service registration not supported on {sys.platform}")


def _register_systemd() -> None:
    """Create a user-level systemd service."""
    bridge_bin = shutil.which("a2a-bridge") or f"{sys.executable} -m a2a_bridge"
    unit_dir = Path.home() / ".config" / "systemd" / "user"
    unit_dir.mkdir(parents=True, exist_ok=True)
    unit_file = unit_dir / "a2a-bridge.service"

    content = f"""\
[Unit]
Description=Tide A2A Bridge
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile={CONFIG_FILE}
ExecStart={bridge_bin} start
Restart=on-failure
RestartSec=5
WorkingDirectory={Path.cwd()}

[Install]
WantedBy=default.target
"""
    unit_file.write_text(content)
    _ok(f"Systemd service written to {unit_file}")

    try:
        subprocess.run(["systemctl", "--user", "daemon-reload"], check=False)
        subprocess.run(["systemctl", "--user", "enable", "a2a-bridge"], check=False)
        _ok("Service enabled. Start with: systemctl --user start a2a-bridge")
    except FileNotFoundError:
        _warn("systemctl not found. Enable manually with the commands above.")


def _register_launchd() -> None:
    """Create a macOS launchd plist."""
    bridge_bin = shutil.which("a2a-bridge") or f"{sys.executable} -m a2a_bridge"
    plist_dir = Path.home() / "Library" / "LaunchAgents"
    plist_dir.mkdir(parents=True, exist_ok=True)
    plist_file = plist_dir / "com.tide.a2a-bridge.plist"

    content = f"""\
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.tide.a2a-bridge</string>
    <key>ProgramArguments</key>
    <array>
        <string>{bridge_bin}</string>
        <string>start</string>
    </array>
    <key>WorkingDirectory</key>
    <string>{Path.cwd()}</string>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>{LOG_FILE}</string>
    <key>StandardErrorPath</key>
    <string>{LOG_FILE}</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>HOME</key>
        <string>{Path.home()}</string>
    </dict>
</dict>
</plist>
"""
    plist_file.write_text(content)
    _ok(f"Launchd plist written to {plist_file}")

    try:
        subprocess.run(["launchctl", "load", str(plist_file)], check=False)
        _ok("Service loaded. Stop with: launchctl unload ~/Library/LaunchAgents/com.tide.a2a-bridge.plist")
    except FileNotFoundError:
        _warn("launchctl not found. Load manually with the command above.")


# ---------------------------------------------------------------------------
# Utility
# ---------------------------------------------------------------------------
def _read_pid() -> Optional[int]:
    if not PID_FILE.exists():
        return None
    try:
        return int(PID_FILE.read_text().strip())
    except (ValueError, OSError):
        return None


def _pid_alive(pid: int) -> bool:
    try:
        os.kill(pid, 0)
        return True
    except (OSError, ProcessLookupError):
        return False


# ---------------------------------------------------------------------------
# Argument parser
# ---------------------------------------------------------------------------
def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="a2a-bridge",
        description="Tide A2A Bridge — run coding agents as A2A protocol servers.",
    )
    parser.add_argument("-v", "--version", action="version", version=f"a2a-bridge {__version__}")

    sub = parser.add_subparsers(dest="command", help="Available commands")

    # setup
    sub.add_parser("setup", help="Interactive setup wizard (configure + detect CLIs)")

    # start
    p_start = sub.add_parser("start", help="Start the bridge server")
    p_start.add_argument("-d", "--daemon", action="store_true", help="Run in background")
    p_start.add_argument("--log-level", default="", help="Override log level (debug/info/warning)")

    # stop
    sub.add_parser("stop", help="Stop the background daemon")

    # status
    sub.add_parser("status", help="Show bridge status and health")

    # doctor
    sub.add_parser("doctor", help="Diagnose common issues")

    return parser


def main(argv: list[str] | None = None) -> None:
    parser = _build_parser()
    args = parser.parse_args(argv)

    if not args.command:
        parser.print_help()
        sys.exit(0)

    handlers = {
        "setup": _cmd_setup,
        "start": _cmd_start,
        "stop": _cmd_stop,
        "status": _cmd_status,
        "doctor": _cmd_doctor,
    }

    handler = handlers.get(args.command)
    if handler:
        handler(args)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
